name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  release_windows:
    needs: create_release
    runs-on: windows-latest

    steps:
      - name: Clear all caches
        run: |
          npm cache clean --force
          pip cache purge
          rmdir /S /Q $env:USERPROFILE\.cache
          rmdir /S /Q $env:USERPROFILE\AppData\Local\Temp
          rmdir /S /Q D:\a\_temp
          rmdir /S /Q D:\a\asp-app\env
          rmdir /S /Q D:\a\asp-app\asp-app\node_modules
        shell: powershell

      - name: Clear GitHub Actions cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/pip
          key: ${{ runner.os }}-clear-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-clear-cache-

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Rebuild Python Virtual Environment
        run: |
          rmdir /S /Q env
          python -m venv env
          .\env\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
        shell: powershell

      - name: Ensure virtual environment is activated and set path
        run: |
          .\env\Scripts\activate
          $env:PATH = "${{ github.workspace }}\env\Scripts;$env:PATH"
          python --version
          pip --version
          where python
          echo $env:PATH
        shell: powershell

      - name: Debug Python Environment Before Build
        run: |
          .\env\Scripts\activate
          python --version
          where python
          echo $env:PATH
          echo $env:PYTHONHOME
          echo $env:PYTHONPATH
          echo $env:PYTHONEXECUTABLE
        shell: powershell

      - name: Build Electron app
        env:
          PATH: D:\a\asp-app\asp-app\env\Scripts;${{ env.PATH }}
          PYTHONHOME: D:\a\asp-app\asp-app\env
          PYTHONPATH: D:\a\asp-app\asp-app\env\Lib\site-packages
          PYTHONEXECUTABLE: D:\a\asp-app\asp-app\env\Scripts\python.exe
          PYTHONNOUSERSITE: '1'
        run: |
          .\env\Scripts\activate
          npm run build
          python --version
          where python
        shell: powershell

      - name: Package Electron app for Windows
        env:
          PATH: D:\a\asp-app\asp-app\env\Scripts;${{ env.PATH }}
          PYTHONHOME: D:\a\asp-app\asp-app\env
          PYTHONPATH: D:\a\asp-app\asp-app\env\Lib\site-packages
          PYTHONEXECUTABLE: D:\a\asp-app\asp-app\env\Scripts\python.exe
          PYTHONNOUSERSITE: '1'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          .\env\Scripts\activate
          npm run electron:build -- --win
          
          if (-Not (Test-Path -Path "dist" -PathType Container)) {
            Write-Error "Build output not found!"
            exit 1
          }
          if (-Not (Test-Path -Path "dist\*.exe" -PathType Leaf)) {
            Write-Error "Installer executable not found!"
            exit 1
          }
        shell: powershell

      - name: Debug Environment Post-Build
        run: |
          .\dist\associated-pension-automation-hub Setup 1.0.83.exe /S /D=D:\a\asp-app\asp-app
          python --version
          where python
          echo $env:PATH
          echo $env:PYTHONHOME
          echo $env:PYTHONPATH
          echo $env:PYTHONEXECUTABLE
        shell: powershell

      - name: Upload Release Assets (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist\associated-pension-automation-hub Setup 1.0.84.exe
          asset_name: associated-pension-automation-hub-1.0.84.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Debug Logs
        uses: actions/upload-artifact@v2
        with:
          name: build-logs
          path: ./debug-logs
