name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Set output using GITHUB_OUTPUT file
      - name: Set upload_url output
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_OUTPUT

  release_windows:
    needs: create_release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Create Firebase credentials file from GitHub secret
        run: |
          $firebaseCreds = @"
          ${{ secrets.FIREBASE_CREDENTIALS }}
          "@
          if ([string]::IsNullOrWhiteSpace($firebaseCreds)) {
            Write-Error "Firebase credentials secret is empty or missing"
            exit 1
          }

          $firebaseCreds = $firebaseCreds -replace "`n", "`r`n"
          Set-Content -Path "firebase-credentials.json" -Value $firebaseCreds
        shell: pwsh

      - name: Check for Python environment
        run: |
          if (-not (Test-Path -Path "env" -PathType Container)) {
            throw "Environment folder 'env' does not exist."
          } else {
            Write-Host "Environment folder 'env' exists."
          }

          if (-not (Test-Path -Path "env/python.exe" -PathType Leaf)) {
            throw "Python executable 'python.exe' not found in 'env/'"
          } else {
            Write-Host "Python executable 'python.exe' found in 'env/'"
          }
        shell: pwsh

      - name: Set Python environment for build
        run: |
          $env:PYTHONHOME = "$PWD/env"
          $env:PATH = "$PWD/env;$env:PATH"
          Write-Host "Python environment set to use 'env/python.exe'."
        shell: pwsh

      - name: Build Electron app
        run: npm run build

      - name: Package Electron app for Windows
        run: |
          export GH_TOKEN="${{ secrets.GH_TOKEN }}"
          npm run electron:build -- --win
        shell: bash

      - name: Upload Release Assets (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist\associated-pension-automation-hub-1.1.52-TEST.exe
          asset_name: associated-pension-automation-hub-1.1.52-TEST.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload `latest.yml` to Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist\latest.yml
          asset_name: latest.yml
          asset_content_type: application/octet-stream
