name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Package Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "GH_TOKEN is set"
          npm run electron:build

      - name: Debug environment variables
        run: printenv

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/*.{exe,dmg,zip}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
